/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as BecomeAGuideRouteImport } from './routes/become-a-guide'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as MessagesBookingIdRouteImport } from './routes/messages.$bookingId'
import { Route as GuidesGuideIdRouteImport } from './routes/guides.$guideId'
import { Route as ExploreSlugRouteImport } from './routes/explore.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BookGuideIdRouteImport } from './routes/book.$guideId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AiThreadIdRouteImport } from './routes/ai.$threadId'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksChatNotificationsRouteImport } from './routes/api/public/hooks/chat-notifications'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAGuideRoute = BecomeAGuideRouteImport.update({
  id: '/become-a-guide',
  path: '/become-a-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MessagesRoute,
} as any)
const MessagesBookingIdRoute = MessagesBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => MessagesRoute,
} as any)
const GuidesGuideIdRoute = GuidesGuideIdRouteImport.update({
  id: '/$guideId',
  path: '/$guideId',
  getParentRoute: () => GuidesRoute,
} as any)
const ExploreSlugRoute = ExploreSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExploreRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BookGuideIdRoute = BookGuideIdRouteImport.update({
  id: '/book/$guideId',
  path: '/book/$guideId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AiThreadIdRoute = AiThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AiRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksChatNotificationsRoute =
  ApiPublicHooksChatNotificationsRouteImport.update({
    id: '/api/public/hooks/chat-notifications',
    path: '/api/public/hooks/chat-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRouteWithChildren
  '/become-a-guide': typeof BecomeAGuideRoute
  '/explore': typeof ExploreRouteWithChildren
  '/faq': typeof FaqRoute
  '/guide': typeof GuideRoute
  '/guides': typeof GuidesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/my-bookings': typeof MyBookingsRoute
  '/settings': typeof SettingsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/ai/$threadId': typeof AiThreadIdRoute
  '/api/chat': typeof ApiChatRoute
  '/book/$guideId': typeof BookGuideIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/messages/$bookingId': typeof MessagesBookingIdRoute
  '/messages/': typeof MessagesIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/chat-notifications': typeof ApiPublicHooksChatNotificationsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRouteWithChildren
  '/become-a-guide': typeof BecomeAGuideRoute
  '/explore': typeof ExploreRouteWithChildren
  '/faq': typeof FaqRoute
  '/guide': typeof GuideRoute
  '/guides': typeof GuidesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/settings': typeof SettingsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/ai/$threadId': typeof AiThreadIdRoute
  '/api/chat': typeof ApiChatRoute
  '/book/$guideId': typeof BookGuideIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/messages/$bookingId': typeof MessagesBookingIdRoute
  '/messages': typeof MessagesIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/chat-notifications': typeof ApiPublicHooksChatNotificationsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRouteWithChildren
  '/become-a-guide': typeof BecomeAGuideRoute
  '/explore': typeof ExploreRouteWithChildren
  '/faq': typeof FaqRoute
  '/guide': typeof GuideRoute
  '/guides': typeof GuidesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/my-bookings': typeof MyBookingsRoute
  '/settings': typeof SettingsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/ai/$threadId': typeof AiThreadIdRoute
  '/api/chat': typeof ApiChatRoute
  '/book/$guideId': typeof BookGuideIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/messages/$bookingId': typeof MessagesBookingIdRoute
  '/messages/': typeof MessagesIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/chat-notifications': typeof ApiPublicHooksChatNotificationsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai'
    | '/become-a-guide'
    | '/explore'
    | '/faq'
    | '/guide'
    | '/guides'
    | '/how-it-works'
    | '/login'
    | '/messages'
    | '/my-bookings'
    | '/settings'
    | '/unsubscribe'
    | '/ai/$threadId'
    | '/api/chat'
    | '/book/$guideId'
    | '/email/unsubscribe'
    | '/explore/$slug'
    | '/guides/$guideId'
    | '/messages/$bookingId'
    | '/messages/'
    | '/lovable/email/suppression'
    | '/api/public/hooks/chat-notifications'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai'
    | '/become-a-guide'
    | '/explore'
    | '/faq'
    | '/guide'
    | '/guides'
    | '/how-it-works'
    | '/login'
    | '/my-bookings'
    | '/settings'
    | '/unsubscribe'
    | '/ai/$threadId'
    | '/api/chat'
    | '/book/$guideId'
    | '/email/unsubscribe'
    | '/explore/$slug'
    | '/guides/$guideId'
    | '/messages/$bookingId'
    | '/messages'
    | '/lovable/email/suppression'
    | '/api/public/hooks/chat-notifications'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai'
    | '/become-a-guide'
    | '/explore'
    | '/faq'
    | '/guide'
    | '/guides'
    | '/how-it-works'
    | '/login'
    | '/messages'
    | '/my-bookings'
    | '/settings'
    | '/unsubscribe'
    | '/ai/$threadId'
    | '/api/chat'
    | '/book/$guideId'
    | '/email/unsubscribe'
    | '/explore/$slug'
    | '/guides/$guideId'
    | '/messages/$bookingId'
    | '/messages/'
    | '/lovable/email/suppression'
    | '/api/public/hooks/chat-notifications'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiRoute: typeof AiRouteWithChildren
  BecomeAGuideRoute: typeof BecomeAGuideRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  FaqRoute: typeof FaqRoute
  GuideRoute: typeof GuideRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  MyBookingsRoute: typeof MyBookingsRoute
  SettingsRoute: typeof SettingsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiChatRoute: typeof ApiChatRoute
  BookGuideIdRoute: typeof BookGuideIdRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksChatNotificationsRoute: typeof ApiPublicHooksChatNotificationsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-guide': {
      id: '/become-a-guide'
      path: '/become-a-guide'
      fullPath: '/become-a-guide'
      preLoaderRoute: typeof BecomeAGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/messages/$bookingId': {
      id: '/messages/$bookingId'
      path: '/$bookingId'
      fullPath: '/messages/$bookingId'
      preLoaderRoute: typeof MessagesBookingIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/guides/$guideId': {
      id: '/guides/$guideId'
      path: '/$guideId'
      fullPath: '/guides/$guideId'
      preLoaderRoute: typeof GuidesGuideIdRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/explore/$slug': {
      id: '/explore/$slug'
      path: '/$slug'
      fullPath: '/explore/$slug'
      preLoaderRoute: typeof ExploreSlugRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$guideId': {
      id: '/book/$guideId'
      path: '/book/$guideId'
      fullPath: '/book/$guideId'
      preLoaderRoute: typeof BookGuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/$threadId': {
      id: '/ai/$threadId'
      path: '/$threadId'
      fullPath: '/ai/$threadId'
      preLoaderRoute: typeof AiThreadIdRouteImport
      parentRoute: typeof AiRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/chat-notifications': {
      id: '/api/public/hooks/chat-notifications'
      path: '/api/public/hooks/chat-notifications'
      fullPath: '/api/public/hooks/chat-notifications'
      preLoaderRoute: typeof ApiPublicHooksChatNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AiRouteChildren {
  AiThreadIdRoute: typeof AiThreadIdRoute
}

const AiRouteChildren: AiRouteChildren = {
  AiThreadIdRoute: AiThreadIdRoute,
}

const AiRouteWithChildren = AiRoute._addFileChildren(AiRouteChildren)

interface ExploreRouteChildren {
  ExploreSlugRoute: typeof ExploreSlugRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreSlugRoute: ExploreSlugRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface GuidesRouteChildren {
  GuidesGuideIdRoute: typeof GuidesGuideIdRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesGuideIdRoute: GuidesGuideIdRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface MessagesRouteChildren {
  MessagesBookingIdRoute: typeof MessagesBookingIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesBookingIdRoute: MessagesBookingIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiRoute: AiRouteWithChildren,
  BecomeAGuideRoute: BecomeAGuideRoute,
  ExploreRoute: ExploreRouteWithChildren,
  FaqRoute: FaqRoute,
  GuideRoute: GuideRoute,
  GuidesRoute: GuidesRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRouteWithChildren,
  MyBookingsRoute: MyBookingsRoute,
  SettingsRoute: SettingsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiChatRoute: ApiChatRoute,
  BookGuideIdRoute: BookGuideIdRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksChatNotificationsRoute: ApiPublicHooksChatNotificationsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
